name: Gatsby Deploy

on:
  push:
    branches:
      - gh-pages
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node Version
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install --prod --pure-lockfile
      - name: Build
        run: yarn run build
        env:
          GATSBY_TOKEN: ${{ secrets.GATSBY_TOKEN }}
      - name: Deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
        env:
          GATSBY_TOKEN: ${{ secrets.GATSBY_TOKEN }}
